server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/userdb
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: user-service
fetchRatingsBaseUrl: http://rating-service/ratings/users/
fetchAllRatingsURL: http://rating-service/ratings

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  health:
    circuitbreakers:
      enabled: true
    endpoints:
      web:
        exposure:
          include: health
    endpoint:
      health:
        show-details: always

resilience4j:
  circuitbreaker:
    instances:
      ratingServiceBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 5
        slidingWindowSize: 10
        slidingWindowType: count_based