server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/userdb
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  application:
    name: user-service
fetchRatingsBaseUrl: http://localhost:8082/ratings/users/
fetchAllRatingsURL: http://localhost:8082/ratings

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
