server:
  port: 8082

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/ratingdb
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
fetchAllHotelsURL: http://localhost:8081/hotels