server:
  port: 8082

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/ratingdb
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: rating-service

#fetchAllHotelsURL: http://hotel-service/hotels

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka