name: CI/CD Flow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Generate module jars
        run: gradle build --exclude-task test
      - name: Build & Push Docker user-service
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          context: ./UserService
          image: ivandvurechenskiy/user-service
          tags: latest
          registry: docker.io
          dockerfile: ./UserService/Dockerfile
          username: ivandvurechenskiy
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build & Push Docker Image hotel-service
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          context: .HotelService/HotelService
          image: ivandvurechenskiy/hotel-service
          tags: latest
          registry: docker.io
          dockerfile: ./Dockerfile
          username: ivandvurechenskiy
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build & Push Docker Image rating service
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          context: ./RatingService
          image: ivandvurechenskiy/rating-service
          tags: latest
          registry: docker.io
          dockerfile: ./RatingService/Dockerfile
          username: ivandvurechenskiy
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build & Push Docker Image rating service
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          context: ./ServiceRegistry
          image: ivandvurechenskiy/service-registry
          tags: latest
          registry: docker.io
          dockerfile: ./ServiceRegistry/Dockerfile
          username: ivandvurechenskiy
          password: ${{ secrets.DOCKER_PASSWORD }}
